hero section
barakadanny/portfolio_html-css pull request #2
Opened 2022-06-29 21:13 UTC by barakadanny

In this pull request I just created the home section (hero)

2022-06-29 22:36 UTC, 1GORDON requested changes
##
## Hi @barakadanny  

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- Good commit messages  ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [x] Please add the correct linter files [Linter files](https://github.com/microverseinc/linters-config/tree/master/html-css)
- [x] Please add the readme file and customise it accordingly [Readme file](https://github.com/microverseinc/readme-template/blob/master/README.md)

### _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 22:36 UTC, 1GORDON commented on index.html
> +            <img class="graph graph-5" src="img/graph_5.png" alt="graph-5">
Great Job so far @barakadanny.🤝. 

- [ ] Try to follow the Figma design provided in the project requirements
- Figma Design
![Figma design](https://user-images.githubusercontent.com/63917725/176554032-7e9fa466-b597-4ed4-9b10-16b99af369dc.PNG)
- Your design
![Your design](https://user-images.githubusercontent.com/63917725/176554122-96a46978-09a2-4847-8e6a-f25ead56e8bc.PNG)

2022-06-30 09:32 UTC, barakadanny commented
note: the official readme file is on the master branch

2022-06-30 09:38 UTC, barakadanny commented
note: The official readme file is on the master branch

2022-06-30 10:01 UTC, aboongm approved these changes
Hi @barakadanny , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![request_changes_1](https://media.giphy.com/media/WFyvwq3xoTTMs/giphy.gif)

## Highlights

## Optional suggestions

[OPTIONAL] Please update the following: 
- In the README.md the link for issues still does not work. 
- The MIT license is also not yet personalize.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 10:30 UTC, merged